% Attention_Modulation_Spread_V4
% Spatial V4 target-minus-distractor d-prime, including background RFs.

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
addpath(repoRoot);
addpath(genpath(fullfile(repoRoot, 'analyses')));
addpath(genpath(fullfile(repoRoot, 'core')));
addpath(genpath(fullfile(repoRoot, 'utils')));

cfg = config();
P = struct();
P.timeIdx = 3;
P.windowMs = [300 500];
P.exampleStimulus = 38;
P.globalSites = (513:768).';
P.pThresh = 0.05;
P.smoothSigmaPx = 15;
P.smoothSupportFraction = 0.01;
P.framePaddingPx = 100;
P.clipRange = [-0.5 0.5];
P.alphaGain = 2.5;
P.contourLineWidth = 4;
P.saveFigure = false;

load(fullfile(cfg.logsDir, 'ObjAtt_lines_monkeyN_20220201_B1.mat')); % ALLCOORDS
load(fullfile(cfg.logsDir, 'RTAB384.mat'));                         % RTAB384
S = load(fullfile(cfg.matDir, 'Tall_V4_lines_N.mat'));
Tall_V4 = S.Tall_V4;
S = load(fullfile(cfg.matDir, 'SNR_capsules_N_d12.mat'));
R3 = S.R;

assert(isequal(double(R3.timeWindows(P.timeIdx,:)), P.windowMs), ...
    'Expected the selected response bin to be 300-500 ms.');
SNRnorm = compute_snr_per_color_region(R3, Tall_V4, P.globalSites);
R3V4 = R3;
R3V4.meanAct = R3.meanAct(P.globalSites,:,:);
R3V4.meanSqAct = R3.meanSqAct(P.globalSites,:,:);
if ~isvector(R3.nTrials)
    R3V4.nTrials = R3.nTrials(P.globalSites,:);
end

optsTD = struct('v1Sites', 1:256, 'timeIdx', P.timeIdx, ...
    'excludeOverlap', true, 'verbose', false);
OUTattention = attention_modulation_V1_3bin( ...
    R3V4, Tall_V4, SNRnorm, optsTD);
keepSites = find(isfinite(OUTattention.pValueTD) & ...
    OUTattention.pValueTD<P.pThresh & isfinite(OUTattention.dprime));

fprintf('Attention-significant V4 sites (pTD < %.3f): %d / 256\n', ...
    P.pThresh, numel(keepSites));
fprintf('Pooled V4 d-prime range at included sites: [%.4g %.4g]\n', ...
    min(OUTattention.dprime(keepSites)), max(OUTattention.dprime(keepSites)));

hAttentionSpread = plot_projected_attention_dprime_on_example_stim( ...
    Tall_V4, ALLCOORDS, RTAB384, P.exampleStimulus, R3V4, SNRnorm, ...
    'TimeBin', P.timeIdx, ...
    'SiteIdx', keepSites, ...
    'CoverageSiteIdx', (1:256).', ...
    'ExcludeOverlap', true, ...
    'SmoothSigmaPx', P.smoothSigmaPx, ...
    'SmoothSupportFraction', P.smoothSupportFraction, ...
    'FramePaddingPx', P.framePaddingPx, ...
    'ClipRange', P.clipRange, ...
    'AlphaGain', P.alphaGain, ...
    'ContourLineWidth', P.contourLineWidth);

label = sprintf('V4 | T-D d'' | %.0f-%.0f ms', P.windowMs);
text(hAttentionSpread.ax, hAttentionSpread.xLimits(1)+14, ...
    hAttentionSpread.yLimits(1)+14, label, ...
    'HorizontalAlignment', 'left', 'VerticalAlignment', 'top', ...
    'FontName', 'Helvetica', 'FontSize', 16, 'FontWeight', 'bold', ...
    'Color', [0.1 0.1 0.1]);
text(hAttentionSpread.ax, hAttentionSpread.xLimits(2)-14, ...
    hAttentionSpread.yLimits(2)-14, ...
    sprintf('N = %d projected points', hAttentionSpread.nRasterPoints), ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'bottom', ...
    'FontName', 'Helvetica', 'FontSize', 12, ...
    'Color', [0.25 0.25 0.25]);
set(hAttentionSpread.fig, 'Name', 'V4 attentional modulation spread', ...
    'NumberTitle', 'off', 'InvertHardcopy', 'off');

if P.saveFigure
    outDir = fullfile(cfg.resultsDir, 'spread');
    if exist(outDir, 'dir')~=7, mkdir(outDir); end
    stem = 'V4_attentional_modulation_dprime_300_500ms';
    savefig(hAttentionSpread.fig, fullfile(outDir,[stem '.fig']));
    print(hAttentionSpread.fig, fullfile(outDir,[stem '.png']), ...
        '-dpng','-r300');
end
