% Visual_Response_Spread_V1_V4
% Run the Nilson V1 and V4 spread analyses and combine them in one figure.

%% Paths and output settings
scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
addpath(repoRoot);
addpath(genpath(fullfile(repoRoot, 'analyses')));
addpath(genpath(fullfile(repoRoot, 'core')));
addpath(genpath(fullfile(repoRoot, 'utils')));

cfg = config();
Pcombined = struct();
Pcombined.saveFigure = true;
Pcombined.outputStem = 'V1_V4_visual_response_spread_smoothed_300_500ms';

%% Run the two established region analyses
run(fullfile(scriptDir, 'Visual_Response_Spread_V1.m'));
hV1 = hSpread;
v1Stats = struct('nPoints', hV1.nPoints, ...
    'nRasterPoints', hV1.nRasterPoints, ...
    'nCoveragePoints', hV1.nCoveragePoints, ...
    'nCoverageRasterPoints', hV1.nCoverageRasterPoints, ...
    'smoothSigmaPx', hV1.smoothSigmaPx, ...
    'colorScaleValues', hV1.colorScaleValues, ...
    'colorScaleRGB', hV1.colorScaleRGB, ...
    'timeWindow', hV1.timeWindow);

run(fullfile(scriptDir, 'Visual_Response_Spread_V4.m'));
hV4 = hSpread;
v4Stats = struct('nPoints', hV4.nPoints, ...
    'nRasterPoints', hV4.nRasterPoints, ...
    'nCoveragePoints', hV4.nCoveragePoints, ...
    'nCoverageRasterPoints', hV4.nCoverageRasterPoints, ...
    'smoothSigmaPx', hV4.smoothSigmaPx, ...
    'timeWindow', hV4.timeWindow);

%% Assemble one two-panel figure
figCombined = figure('Color', 'w', ...
    'Name', 'Nilson visual-response spread | V1 and V4', ...
    'NumberTitle', 'off', ...
    'InvertHardcopy', 'off', ...
    'Position', [50 100 1600 650]);

axV1 = axes('Parent', figCombined, 'Position', [0.01 0.02 0.485 0.96]);
copy_spread_panel(hV1.ax, axV1);

axV4 = axes('Parent', figCombined, 'Position', [0.505 0.02 0.485 0.96]);
copy_spread_panel(hV4.ax, axV4);

scaleAx = axes('Parent', figCombined, 'Position', [0.31 0.905 0.17 0.025]);
image(scaleAx, [v1Stats.colorScaleValues(1) v1Stats.colorScaleValues(end)], ...
    [0 1], v1Stats.colorScaleRGB);
set(scaleAx, ...
    'Box', 'on', ...
    'Color', 'w', ...
    'FontName', 'Helvetica', ...
    'FontSize', 9, ...
    'Layer', 'top', ...
    'TickDir', 'out', ...
    'XLim', [v1Stats.colorScaleValues(1) v1Stats.colorScaleValues(end)], ...
    'XTick', [-1 0 1 2], ...
    'YDir', 'normal', ...
    'YLim', [0 1], ...
    'YTick', []);
xlabel(scaleAx, 'Normalized response (z)', ...
    'FontName', 'Helvetica', 'FontSize', 9);

close(hV1.fig);
close(hV4.fig);
drawnow;

hSpreadCombined = struct();
hSpreadCombined.fig = figCombined;
hSpreadCombined.axV1 = axV1;
hSpreadCombined.axV4 = axV4;
hSpreadCombined.scaleAx = scaleAx;
hSpreadCombined.v1 = v1Stats;
hSpreadCombined.v4 = v4Stats;

%% Save the requested combined figure
if Pcombined.saveFigure
    spreadResultsDir = fullfile(cfg.resultsDir, 'spread');
    if exist(spreadResultsDir, 'dir') ~= 7
        mkdir(spreadResultsDir);
    end
    figPath = fullfile(spreadResultsDir, [Pcombined.outputStem '.fig']);
    pngPath = fullfile(spreadResultsDir, [Pcombined.outputStem '.png']);
    savefig(figCombined, figPath);
    print(figCombined, pngPath, '-dpng', '-r300');
    fprintf('Saved combined spread figure:\n  %s\n  %s\n', figPath, pngPath);
end

function copy_spread_panel(sourceAx, targetAx)
copyobj(allchild(sourceAx), targetAx);
set(targetAx, ...
    'Color', 'w', ...
    'XLim', sourceAx.XLim, ...
    'YLim', sourceAx.YLim, ...
    'YDir', sourceAx.YDir, ...
    'DataAspectRatio', sourceAx.DataAspectRatio, ...
    'Visible', 'off');
axis(targetAx, 'image');
axis(targetAx, 'off');
end
