% Plot_Comp4_Aligned_Cue_Locations
% Show where the central cue falls after aligning every comp4 monkey and
% crocodile to the canonical object geometry used to generate the stimuli.

%% Paths
scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
addpath(repoRoot);

cfg = config();
comp4Dir = fullfile(cfg.resultsRoot, 'Comp4');
metadataDir = fullfile(comp4Dir, 'metadata');
figuresDir = fullfile(comp4Dir, 'figures');
if exist(metadataDir, 'dir') ~= 7
    mkdir(metadataDir);
end
if exist(figuresDir, 'dir') ~= 7
    mkdir(figuresDir);
end

conditionFile = fullfile(metadataDir, 'comp4_stimulus_conditions.csv');
geometryFile = fullfile(cfg.extrasRoot, 'monkeyN', '_logs', 'temp_figs.mat');
logFile = fullfile(cfg.extrasRoot, 'monkeyN', '_logs', ...
    'ObjAtt_Shapes_comp4_monkeyN_20220502_B1.mat');
trialFile = fullfile(cfg.dataRoot, 'Mr Nilson', 'comp4', ...
    'ObjAtt_Shapes_comp4_MUA_trials.mat');

assert(exist(conditionFile, 'file') == 2, ...
    'Run Check_Comp4_Stimulus_Quartets.m first.');
assert(exist(geometryFile, 'file') == 2, 'Missing %s.', geometryFile);
assert(exist(logFile, 'file') == 2, 'Missing %s.', logFile);
assert(exist(trialFile, 'file') == 2, 'Missing %s.', trialFile);

%% Load canonical objects, per-stimulus coordinates, and trial metadata
stimulusConditions = readtable(conditionFile);
G = load(geometryFile, 'temp_figures');
C = load(logFile, 'ALLCOORDS');

crocodile = G.temp_figures.class1_complexity4;
monkey = G.temp_figures.class2_complexity4;
assert(size(crocodile.cues, 1) == 2 && size(monkey.cues, 1) == 2, ...
    'Expected exactly two canonical cue locations per object.');

M = matfile(trialFile);
trialInfo = double(M.ALLMAT);
assert(size(trialInfo, 2) >= 8, 'ALLMAT must contain the original 8 stimulus columns.');

% Original stimulus columns:
% 1 stimulus, 2 array, 3 cones, 4 foreground, 5 class,
% 6 angle, 7 central-cue index (cc), 8 color.
assert(all(ismember(unique(trialInfo(:,7)), [1 2])), ...
    'ALLMAT column 7 contains values other than cue indices 1 and 2.');

%% Recover the central-cue choice and display coordinates for each stimulus
nStimuli = height(stimulusConditions);
assert(nStimuli == 320, 'Expected 320 stimulus metadata rows.');

primaryCueIndex = nan(nStimuli, 1);
centralCueDisplayX = nan(nStimuli, 1);
centralCueDisplayY = nan(nStimuli, 1);

for stim = 1:nStimuli
    trialRows = trialInfo(:,1) == stim;
    assert(any(trialRows), 'Stimulus %d is absent from ALLMAT.', stim);

    cueValues = unique(trialInfo(trialRows, 7));
    assert(numel(cueValues) == 1, ...
        'Stimulus %d has inconsistent central-cue indices.', stim);
    primaryCueIndex(stim) = cueValues;

    fieldName = sprintf('stim_%d', stim);
    assert(isfield(C.ALLCOORDS, fieldName), ...
        'ALLCOORDS is missing %s.', fieldName);
    centralCue = double(C.ALLCOORDS.(fieldName).s(:));
    centralCueDisplayX(stim) = centralCue(1);
    centralCueDisplayY(stim) = centralCue(2);

    rows = trialInfo(trialRows, :);
    assert(all(rows(:,2) == stimulusConditions.array(stim)), ...
        'Array mismatch for stimulus %d.', stim);
    assert(all(rows(:,3) == stimulusConditions.cones(stim)), ...
        'Cone-distance mismatch for stimulus %d.', stim);
    assert(all(rows(:,5) == stimulusConditions.objectClass(stim)), ...
        'Object-class mismatch for stimulus %d.', stim);
end

% The primary/array object uses cue cc as s. The secondary object was
% generated by mapping its canonical cue 1 onto that same central cue s.
crocodileCueIndex = ones(nStimuli, 1);
monkeyCueIndex = ones(nStimuli, 1);
isCrocodilePrimary = stimulusConditions.objectClass == 1;
isMonkeyPrimary = stimulusConditions.objectClass == 2;
crocodileCueIndex(isCrocodilePrimary) = primaryCueIndex(isCrocodilePrimary);
monkeyCueIndex(isMonkeyPrimary) = primaryCueIndex(isMonkeyPrimary);

crocodileCueX = crocodile.cues(crocodileCueIndex, 1);
crocodileCueY = crocodile.cues(crocodileCueIndex, 2);
monkeyCueX = monkey.cues(monkeyCueIndex, 1);
monkeyCueY = monkey.cues(monkeyCueIndex, 2);

cueGeometry = stimulusConditions;
cueGeometry.primaryCueIndex = primaryCueIndex;
cueGeometry.centralCueDisplayX = centralCueDisplayX;
cueGeometry.centralCueDisplayY = centralCueDisplayY;
cueGeometry.crocodileCueIndex = crocodileCueIndex;
cueGeometry.crocodileCueX = crocodileCueX;
cueGeometry.crocodileCueY = crocodileCueY;
cueGeometry.monkeyCueIndex = monkeyCueIndex;
cueGeometry.monkeyCueX = monkeyCueX;
cueGeometry.monkeyCueY = monkeyCueY;

%% Plot the two canonical objects and their possible central-cue locations
h = figure('Color', 'w', 'Name', 'Comp4 aligned central cue locations', ...
    'NumberTitle', 'off', 'Position', [100 100 1250 560]);
layout = tiledlayout(h, 1, 2, 'Padding', 'compact', 'TileSpacing', 'compact');

plotCanonicalObject(nexttile(layout), crocodile, crocodileCueIndex, ...
    'Crocodile');
plotCanonicalObject(nexttile(layout), monkey, monkeyCueIndex, 'Monkey');
title(layout, 'Central cue after canonical object alignment', ...
    'FontWeight', 'bold');

%% Save compact geometry and figure to Dropbox
writetable(cueGeometry, ...
    fullfile(metadataDir, 'comp4_cue_geometry.csv'));
save(fullfile(metadataDir, 'comp4_cue_geometry.mat'), ...
    'cueGeometry', 'crocodile', 'monkey');
savefig(h, fullfile(figuresDir, 'comp4_aligned_central_cues.fig'));
print(h, fullfile(figuresDir, 'comp4_aligned_central_cues.png'), ...
    '-dpng', '-r300');

fprintf('Saved cue geometry to: %s\n', metadataDir);
fprintf('Saved aligned-cue figure to: %s\n', figuresDir);


function plotCanonicalObject(ax, objectGeometry, cueIndex, objectName)
hold(ax, 'on');
fill(ax, objectGeometry.X, objectGeometry.Y, [0.84 0.86 0.82], ...
    'EdgeColor', [0.18 0.23 0.20], 'LineWidth', 1.5);

cueColors = [0.10 0.45 0.70; 0.88 0.36 0.16];
for cue = 1:2
    count = nnz(cueIndex == cue);
    scatter(ax, objectGeometry.cues(cue,1), objectGeometry.cues(cue,2), ...
        150, cueColors(cue,:), 'filled', 'MarkerEdgeColor', 'w', ...
        'LineWidth', 1.5);
    text(ax, objectGeometry.cues(cue,1), objectGeometry.cues(cue,2), ...
        sprintf('  Cue %d\n  n = %d', cue, count), ...
        'FontWeight', 'bold', 'VerticalAlignment', 'middle');
end

axis(ax, 'equal');
axis(ax, 'off');
title(ax, objectName, 'FontWeight', 'bold');
end
